# Generated by Django 5.0.1 on 2024-07-06 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('project_size', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Site Survey', 'Site Survey'), ('Engineering Design', 'Engineering Design'), ('Proposal', 'Proposal'), ('Commercials Finalized', 'Commercials Finalized'), ('PO Received', 'PO Received'), ('Cold', 'Cold')], max_length=100, null=True)),
                ('next_action', models.CharField(blank=True, choices=[('Site Survey', 'Site Survey'), ('Engineering Design', 'Engineering Design'), ('Proposal', 'Proposal'), ('Meeting', 'Meeting'), ('Follow-up', 'Follow-up')], max_length=100, null=True)),
                ('next_action_scheduled_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
