# Generated by Django 5.0.1 on 2024-07-06 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Networking Event', 'Networking Event'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
