# Generated by Django 5.0.6 on 2024-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_leads_owner_alter_leads_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'Leads'},
        ),
        migrations.RemoveField(
            model_name='leads',
            name='next_action_owner',
        ),
        migrations.AddField(
            model_name='leads',
            name='country',
            field=models.CharField(blank=True, choices=[('Algeria', 'Algeria'), ('Angola', 'Angola'), ('Benin', 'Benin'), ('Botswana', 'Botswana'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cabo Verde', 'Cabo Verde'), ('Cameroon', 'Cameroon'), ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Djibouti', 'Djibouti'), ('Egypt', 'Egypt'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Eswatini', 'Eswatini'), ('Ethiopia', 'Ethiopia'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Ivory Coast', 'Ivory Coast'), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Rwanda', 'Rwanda'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Sudan', 'South Sudan'), ('Sudan', 'Sudan'), ('Tanzania', 'Tanzania'), ('Togo', 'Togo'), ('Tunisia', 'Tunisia'), ('Uganda', 'Uganda'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Automobile', 'Automobile'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Energy', 'Energy'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('IT', 'IT'), ('Manufacturing', 'Manufacturing'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Telecom', 'Telecom'), ('Transportation', 'Transportation'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='project_type',
            field=models.CharField(blank=True, choices=[('EPC', 'EPC'), ('ETA', 'ETA'), ('Tender', 'Tender'), ('Lease', 'Lease')], max_length=100, null=True),
        ),
    ]
