# Generated by Django 5.1 on 2024-08-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_leads_owner_alter_leads_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'Leads'},
        ),
    ]
