# Generated by Django 5.0.7 on 2024-08-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leads_next_action_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='stage',
            field=models.CharField(blank=True, choices=[('New Lead', 'New Lead'), ('Site Visit', 'Site Visit'), ('Design & Proposal', 'Design & Proposal'), ('Submission Proposal', 'Submission Proposal'), ('Update', 'Update'), ('Meeting', 'Meeting'), ('Won', 'Won'), ('Proposal Update', 'Proposal Update')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(blank=True, choices=[('Neutral', 'Neutral'), ('Warm', 'Warm'), ('Won', 'Won')], max_length=100, null=True),
        ),
    ]
