# Generated by Django 5.0.6 on 2024-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leads_options_remove_leads_next_action_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Site Survey', 'Site Survey'), ('Engineering Design', 'Engineering Design'), ('Proposal', 'Proposal'), ('Commercials Finalized', 'Commercials Finalized'), ('PO Received', 'PO Received'), ('Cold', 'Cold'), ('Won', 'Won')], max_length=100, null=True),
        ),
    ]
