# Generated by Django 5.1 on 2024-08-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_leads_stage_alter_leads_next_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='next_action',
            field=models.CharField(blank=True, choices=[('New Lead', 'New Lead'), ('Site Visit', 'Site Visit'), ('Design & Proposal', 'Design & Proposal'), ('Submission Proposal', 'Submission Proposal'), ('Meeting', 'Meeting'), ('Proposal Update', 'Proposal Update')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(blank=True, choices=[('Neutral', 'Neutral'), ('Warm', 'Warm'), ('Won', 'Won'), ('Cold', 'Cold'), ('Fresh', 'Fresh')], max_length=100, null=True),
        ),
    ]
