# Generated by Django 5.0.6 on 2024-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leads_due_date_alter_leads_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='bess_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='project_type',
            field=models.CharField(blank=True, choices=[('EPC', 'EPC'), ('ETA', 'ETA'), ('PPA', 'PPA'), ('EPC & PPA', 'EPC & PPA'), ('EPC & LEASE', 'EPC & LEASE'), ('PPA & LEASE', 'PPA & LEASE'), ('EPC & PPA & LEASE', 'EPC & PPA & LEASE'), ('Lease', 'Lease')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.CharField(blank=True, choices=[('Tender', 'Tender'), ('Internal', 'Internal'), ('Channel Partner', 'Channel Patner'), ('Organic', 'Organic')], max_length=100, null=True),
        ),
    ]
